name: Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - main

jobs:
  validate-pr-title:
    name: Validate PR Title
    permissions:
      pull-requests: read
    uses: openfga/.github/.github/workflows/pr-title-check.yml@835baf31562809ad9eb884c73efc5b79318f700f # pin@main

  test:
    name: Test
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml
